version: "3.8"
services:
  nmt:
    container_name: nmt 
    volumes:
      - ./nmt:/root/nmt
    ports:
      - '8896:8888'
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
    user:
     "root"
    build: ./

